//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 225 1 1.
        /// </summary>
        internal static string Id1 {
            get {
                return ResourceManager.GetString("Id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 263 293 1 10.
        /// </summary>
        internal static string Id10 {
            get {
                return ResourceManager.GetString("Id10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 321 280 1 11.
        /// </summary>
        internal static string Id11 {
            get {
                return ResourceManager.GetString("Id11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 367 280 1 12.
        /// </summary>
        internal static string Id12 {
            get {
                return ResourceManager.GetString("Id12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 419 280 1 13.
        /// </summary>
        internal static string Id13 {
            get {
                return ResourceManager.GetString("Id13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 463 267 1 14.
        /// </summary>
        internal static string Id14 {
            get {
                return ResourceManager.GetString("Id14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 497 240 1 15.
        /// </summary>
        internal static string Id15 {
            get {
                return ResourceManager.GetString("Id15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 531 213 1 16.
        /// </summary>
        internal static string Id16 {
            get {
                return ResourceManager.GetString("Id16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 561 190 1 17.
        /// </summary>
        internal static string Id17 {
            get {
                return ResourceManager.GetString("Id17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 588 168 1 18.
        /// </summary>
        internal static string Id18 {
            get {
                return ResourceManager.GetString("Id18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 38 2 19.
        /// </summary>
        internal static string Id19 {
            get {
                return ResourceManager.GetString("Id19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 256 1 2.
        /// </summary>
        internal static string Id2 {
            get {
                return ResourceManager.GetString("Id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 70 2 20.
        /// </summary>
        internal static string Id20 {
            get {
                return ResourceManager.GetString("Id20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 102 2 21.
        /// </summary>
        internal static string Id21 {
            get {
                return ResourceManager.GetString("Id21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 133 2 22.
        /// </summary>
        internal static string Id22 {
            get {
                return ResourceManager.GetString("Id22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 165 2 23.
        /// </summary>
        internal static string Id23 {
            get {
                return ResourceManager.GetString("Id23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 196 2 24.
        /// </summary>
        internal static string Id24 {
            get {
                return ResourceManager.GetString("Id24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 228 2 25.
        /// </summary>
        internal static string Id25 {
            get {
                return ResourceManager.GetString("Id25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 257 2 26.
        /// </summary>
        internal static string Id26 {
            get {
                return ResourceManager.GetString("Id26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 337 2 27.
        /// </summary>
        internal static string Id27 {
            get {
                return ResourceManager.GetString("Id27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 382 2 28.
        /// </summary>
        internal static string Id28 {
            get {
                return ResourceManager.GetString("Id28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 427 2 29.
        /// </summary>
        internal static string Id29 {
            get {
                return ResourceManager.GetString("Id29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 285 1 3.
        /// </summary>
        internal static string Id3 {
            get {
                return ResourceManager.GetString("Id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 470 2 30.
        /// </summary>
        internal static string Id30 {
            get {
                return ResourceManager.GetString("Id30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320 515 2 31.
        /// </summary>
        internal static string Id31 {
            get {
                return ResourceManager.GetString("Id31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 285 548 2 32.
        /// </summary>
        internal static string Id32 {
            get {
                return ResourceManager.GetString("Id32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 222 548 2 33.
        /// </summary>
        internal static string Id33 {
            get {
                return ResourceManager.GetString("Id33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 171 548 2 34.
        /// </summary>
        internal static string Id34 {
            get {
                return ResourceManager.GetString("Id34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128 548 2 35.
        /// </summary>
        internal static string Id35 {
            get {
                return ResourceManager.GetString("Id35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 548 2 36.
        /// </summary>
        internal static string Id36 {
            get {
                return ResourceManager.GetString("Id36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 162 133 3 37.
        /// </summary>
        internal static string Id37 {
            get {
                return ResourceManager.GetString("Id37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192 181 3 38.
        /// </summary>
        internal static string Id38 {
            get {
                return ResourceManager.GetString("Id38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 218 222 3 39.
        /// </summary>
        internal static string Id39 {
            get {
                return ResourceManager.GetString("Id39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 325 1 4.
        /// </summary>
        internal static string Id4 {
            get {
                return ResourceManager.GetString("Id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 251 274 3 40.
        /// </summary>
        internal static string Id40 {
            get {
                return ResourceManager.GetString("Id40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 343 337 3 41.
        /// </summary>
        internal static string Id41 {
            get {
                return ResourceManager.GetString("Id41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365 350 3 42.
        /// </summary>
        internal static string Id42 {
            get {
                return ResourceManager.GetString("Id42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 384 375 3 43.
        /// </summary>
        internal static string Id43 {
            get {
                return ResourceManager.GetString("Id43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 401 3 44.
        /// </summary>
        internal static string Id44 {
            get {
                return ResourceManager.GetString("Id44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 422 429 3 45.
        /// </summary>
        internal static string Id45 {
            get {
                return ResourceManager.GetString("Id45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 443 457 3 46.
        /// </summary>
        internal static string Id46 {
            get {
                return ResourceManager.GetString("Id46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 463 485 3 47.
        /// </summary>
        internal static string Id47 {
            get {
                return ResourceManager.GetString("Id47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480 507 3 48.
        /// </summary>
        internal static string Id48 {
            get {
                return ResourceManager.GetString("Id48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 496 530 3 49.
        /// </summary>
        internal static string Id49 {
            get {
                return ResourceManager.GetString("Id49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 325 1 5.
        /// </summary>
        internal static string Id5 {
            get {
                return ResourceManager.GetString("Id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 524 547 3 50.
        /// </summary>
        internal static string Id50 {
            get {
                return ResourceManager.GetString("Id50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 551 547 3 51.
        /// </summary>
        internal static string Id51 {
            get {
                return ResourceManager.GetString("Id51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 577 547 3 52.
        /// </summary>
        internal static string Id52 {
            get {
                return ResourceManager.GetString("Id52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115 325 1 6.
        /// </summary>
        internal static string Id6 {
            get {
                return ResourceManager.GetString("Id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 156 325 1 7.
        /// </summary>
        internal static string Id7 {
            get {
                return ResourceManager.GetString("Id7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 193 325 1 8.
        /// </summary>
        internal static string Id8 {
            get {
                return ResourceManager.GetString("Id8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 231 325 1 9.
        /// </summary>
        internal static string Id9 {
            get {
                return ResourceManager.GetString("Id9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 3 10 40.
        /// </summary>
        internal static string Pair1 {
            get {
                return ResourceManager.GetString("Pair1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 2 11 26.
        /// </summary>
        internal static string Pair2 {
            get {
                return ResourceManager.GetString("Pair2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 3 27 41.
        /// </summary>
        internal static string Pair3 {
            get {
                return ResourceManager.GetString("Pair3", resourceCulture);
            }
        }
    }
}
